<template>
  <div class="min-h-screen bg-slate-900 py-8 px-4">
    <div class="max-w-4xl mx-auto">
      <!-- Header -->
      <div class="text-center mb-8">
        <h1 class="text-3xl font-bold text-white mb-2">The Game Before the Game</h1>
        <p class="text-slate-400">The AI-generated pregame show written by fans</p>
      </div>

      <!-- Loading State -->
      <div v-if="matchups.loading" class="text-center py-20">
        <div class="animate-spin w-8 h-8 border-2 border-orange-500 border-t-transparent rounded-full mx-auto mb-4"></div>
        <p class="text-slate-400">Loading...</p>
      </div>

      <!-- No Video State -->
      <div v-else-if="!videoUrl" class="text-center py-20">
        <div class="text-6xl mb-4">🎬</div>
        <h2 class="text-xl text-white mb-2">Show Coming Soon</h2>
        <p class="text-slate-400 mb-4">
          {{ matchups.hasActiveMatchup 
            ? 'The pregame show is being generated. Check back soon!' 
            : 'No matchup available.' 
          }}
        </p>
        <router-link to="/" class="text-orange-500 hover:underline">
          Return home
        </router-link>
      </div>

      <!-- Video Player -->
      <div v-else>
        <div class="rounded-xl overflow-hidden bg-black mb-8">
          <video 
            ref="videoRef"
            :src="videoUrl"
            controls
            autoplay
            class="w-full aspect-video"
            poster="/images/Gemini_Generated_Image_uy5u78uy5u78uy5u-3.png"
          >
            Your browser does not support the video tag.
          </video>
        </div>

        <!-- Matchup Info -->
        <div class="card mb-8">
          <div class="flex items-center justify-between mb-4">
            <div>
              <p class="text-orange-500 font-bold text-sm">SUPER BOWL LX</p>
              <h2 class="text-xl text-white font-bold">
                {{ matchups.currentMatchup?.home_team }} vs {{ matchups.currentMatchup?.away_team }}
              </h2>
            </div>
            <p class="text-slate-400">February 8, 2026</p>
          </div>
          <p class="text-slate-400">
            This anime-style pregame show was generated by AI based on community votes. 
            This is YOUR story — the game the fans wrote together!
          </p>
        </div>

        <!-- Actions -->
        <div class="flex flex-wrap gap-4 justify-center">
          <router-link 
            v-if="auth.isLoggedIn" 
            to="/results" 
            class="btn-secondary"
          >
            View Your Scorecard
          </router-link>
          <button @click="copyLink" class="btn-secondary flex items-center gap-2">
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.368 2.684 3 3 0 00-5.368-2.684z" />
            </svg>
            {{ copied ? 'Link Copied!' : 'Share' }}
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useAuthStore } from '@/stores/auth'
import { useMatchupsStore } from '@/stores/matchups'

const auth = useAuthStore()
const matchups = useMatchupsStore()
const videoRef = ref<HTMLVideoElement | null>(null)
const copied = ref(false)

const videoUrl = computed(() => matchups.currentMatchup?.video_url_trailer || null)

async function copyLink() {
  try {
    await navigator.clipboard.writeText(window.location.href)
    copied.value = true
    setTimeout(() => { copied.value = false }, 2000)
  } catch {
    // Fallback for older browsers
    const input = document.createElement('input')
    input.value = window.location.href
    document.body.appendChild(input)
    input.select()
    document.execCommand('copy')
    document.body.removeChild(input)
    copied.value = true
    setTimeout(() => { copied.value = false }, 2000)
  }
}

onMounted(async () => {
  await matchups.fetchCurrentMatchup()
})
</script>
